### ISSUE TITLE
Highlight Chester County on map

### ISSUE THREAD

**Issue by scottwink** [mshareef123/CCFarmApp#32]

**Comment by eaziz** [comment]
I am afraid that it can't be done using regular google maps app, since according to documentation county, city and any custom administrative boundaries are defined manually using lat/long map. If we are to use these maps not everything will work and here is the link for custom map that highlits Chester County https://www.google.com/maps/d/viewer?mid=z_MXwZWUJnvA.kOlUa9pAFVX8&hl=en_US as you can see since it's boundaries handpicked by someone who also included custom markers on it we can't utilize it for our own benefit without noise. I we are to recreate Chester County map by ourselves it is going to be big undertaking that we do not have time and resources to do.

**Comment by enived** [comment]
I think we should still be able to do search bias on the box using long /
lat boundary box. I'm still working on this

**Comment by enived** [comment]
Completed
